version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      target: runner
    restart: always
    command: npm run dev
    env_file:
      - .env
    ports:
      - 3000:3000